CREATE TABLE LOCATIONS(
    ID SERIAL PRIMARY KEY,
    X REAL,
    Y DOUBLE PRECISION,
    Z INTEGER NOT NULL
);

CREATE TABLE COORDINATES(
    ID SERIAL PRIMARY KEY,
    X BIGINT NOT NULL,
    Y BIGINT
);

CREATE TABLE PERSONS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    EYE_COLOR TEXT NOT NULL CHECK (EYE_COLOR IN ('RED', 'BROWN', 'BLACK')),
    HAIR_COLOR TEXT NOT NULL CHECK (HAIR_COLOR IN ('RED', 'BROWN', 'BLACK')),
    LOCATION_ID INTEGER NOT NULL REFERENCES LOCATIONS(ID),
    BIRTHDAY TIMESTAMPTZ,
    WEIGHT BIGINT NOT NULL CHECK (WEIGHT > 0),
    PASSPORT_ID TEXT CHECK (LENGTH(PASSPORT_ID) >= 4)
);

CREATE TABLE MOVIES(
    ID SERIAL PRIMARY KEY,                       
    NAME TEXT NOT NULL,
    COORDINATES_ID INTEGER NOT NULL REFERENCES COORDINATES(ID),
    CREATION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    OSCARS_COUNT BIGINT NOT NULL CHECK (OSCARS_COUNT >= 0),
    BUDGET INTEGER CHECK (BUDGET > 0),
    TOTAL_BOX_OFFICE REAL CHECK (TOTAL_BOX_OFFICE > 0), 
    MPAA_RATING TEXT CHECK (MPAA_RATING IN ('PG_13', 'R', 'NC_17')),                           
    DIRECTOR_ID INTEGER REFERENCES PERSONS(ID),          
    SCREENWRITER_ID INTEGER REFERENCES PERSONS(ID),      
    OPERATOR_ID INTEGER REFERENCES PERSONS(ID),          
    LENGTH INTEGER NOT NULL CHECK (LENGTH > 0),     
    GOLDEN_PALM_COUNT INTEGER CHECK (GOLDEN_PALM_COUNT > 0), 
    USA_BOX_OFFICE DOUBLE PRECISION CHECK (USA_BOX_OFFICE > 0), 
    GENRE TEXT   CHECK (GENRE IN ('DRAMA', 'COMEDY', 'ADVENTURE', 'THRILLER', 'HORROR'))                                
);

CREATE TABLE OPERATIONS(
    ID SERIAL PRIMARY KEY,
    COMPLETED BOOLEAN NOT NULL,
    USERNAME TEXT NOT NULL,
    COUNT INTEGER CHECK(COUNT >= 0)
);